[kubernetes]
format = 'on [â›µ $context \($namespace\)](dimmed green) '
disabled = false

[kubernetes.context_aliases]
docker-desktop                                            = "local"

[gcloud]
format = "[$symbol $active]($style) "
style = "bold yellow"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[golang]
format = "via [ğŸ¹ $version](bold cyan) "

[line_break]
disabled = false
