[tools]
bat = "latest"
claude = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fnm = "latest"
fzf = "latest"
jq = "latest"
just = "latest"
ripgrep = "latest"
uv = "latest"

[tool_alias]
fnm = "aqua:Schniz/fnm"

[settings]
plugin_autoupdate_last_check_duration = '1 week'
